Repository The-Shivam-garg/BigB-E-learn-Websit-e, pull requests merged in 2022-10, with the labels that each got.

#429 fixed the design of login page
  log in/Login.html
  log in/login.css
Labels: Level1, hacktoberfest

#433 Bug fixed in hover menu in small screen
  navbar.css
Labels: bug, hacktoberfest

#454 fix : Added autofocus tag
  log in/Login.html
Labels: hacktoberfest

#452 Update readme.md
  readme.md
Labels: hacktoberfest

#447 Added slideshow effect in teach page
  teach-on-bigb/teach.js
Labels: hacktoberfest

#456 fix : Signup responsiveness
  .vscode/settings.json
  log in/login.css
  log in/style.css
Labels: hacktoberfest

#460 Home responsive fix
  css/main.css
Labels: hacktoberfest

#457 U.I made Even
  feature-pg/feature.html
  feature-pg/features.css
Labels: hacktoberfest

#464 Correct the Image Position
  feature-pg/feature.html
Labels: hacktoberfest

#466 fixed footer responsiveness
  style.css
Labels: hacktoberfest

#467 Update Courses page with alt text
  Course/Courses.html
Labels: hacktoberfest

#477 Fixed the bug of Sign in option
  contact/contact.html
Labels: hacktoberfest

#480 Added footer to the counselling page
  counselling/ counselling.html
  counselling/counselling.css
Labels: hacktoberfest

#492 Nav links and Images in Why Education Section fixed.
  css/main.css
  style.css
Labels: hacktoberfest

#483 Aligned boxes in blog page
  Blog/blog.html
  Blog/css/Style.css
Labels: hacktoberfest

#490 Changes in U.I of feature section in blog and top button
  feature-pg/feature.html
Labels: hacktoberfest

#486 added lazy loading to reduce initial load time
  index.html
Labels: hacktoberfest

#500 Nav links on hover fixed
  navbar.css
Labels: hacktoberfest

#443 Made some changes in Navbar and Contact section
  Course/Courses.html
  contact/css/style.css
  css/main.css
  index.html
  navbar.css
  style.css
Labels: hacktoberfest

#504 overlay click to close modal , overlay ui changes
  css/responsive.css
  index.html
  js/script3.js
  style.css
Labels: hacktoberfest

#511 BigB logo issue resolved in contact page
  contact/contact.html
Labels: hacktoberfest

#513 Displaced theme toggle button is fixed
  Course/Courses.html
  Course/css/style.css
Labels: hacktoberfest

#497 Overflow Fixed on teach.html
  navbar.css
  style.css
  teach-on-bigb/teach.css
Labels: hacktoberfest

#522 Fix section below navbar
  Course/Courses.html
  Course/css/style.css
Labels: hacktoberfest

#523 Modified Footer Section
  index.html
  style.css
Labels: hacktoberfest

#524 fix for intro section and h1 text
  Course/Courses.html
Labels: hacktoberfest

#520 New branch
  index.html
  style.css
Labels: hacktoberfest
