Repository The-Shivam-garg/BigB-E-learn-Websit-e, pull requests merged in 2022-05, with the labels that each got.

#368 Improved subscribe section
  css/main.css
  css/responsive.css
  css/utility.css
Labels: good first issue, Level1, GSSoC22

#371 Resolved the bug in join course
  index.html
Labels: good first issue, Level1, GSSoC22

#373 Updated the email address
  Course/subjects/computer_courses.html
  Course/subjects/gate.html
  Course/subjects/jee.html
  Course/subjects/neet.html
Labels: good first issue, Level1, GSSoC22

#372 Converted cursor to pointer in "What we offer section"
  css/main.css
Labels: bug, good first issue, Level1, GSSoC22

#375 Redesigned teach page
  .DS_Store
  Blog/.DS_Store
  Course/.DS_Store
  Events/.DS_Store
  Resource_Page/.DS_Store
  about/.DS_Store
  community/.DS_Store
  contact/.DS_Store
  teach-on-bigb/images/right-quotes-sign-new.png
  teach-on-bigb/images/right-quotes-sign.png
  teach-on-bigb/teach.css
  teach-on-bigb/teach.html
Labels: enhancement, Level2, GSSoC22

#374 Updated nav and scrollbar
  feature-pg/assets/css/style.css
  feature-pg/feature.html
Labels: good first issue, Level1, GSSoC22

#381 Added some new courses to the website
  Course/Courses.html
  Course/images/courses/Account-based-marketing.jpg
  Course/images/courses/Brand-management cover.jpg
  Course/images/courses/Digital Marketing cover.jpg
  Course/images/courses/Invoice.png
  Course/images/courses/Marketing-Funnel.jpeg
  Course/images/courses/Marketing.jpg
  Course/images/courses/Results-On-Investment-ROI.jpg
  Course/images/courses/balance sheet.jpg
  Course/images/courses/brand-management.png
  Course/images/courses/cash flow.jpg
  Course/images/courses/cybersec.jpg
  Course/images/courses/cybersec2.jpg
  Course/images/courses/data science.jpg
  Course/images/courses/datasc playlist.jpg
  Course/images/courses/digital marketing course.jpg
  Course/images/courses/inbound-marketing.jpg
  Course/images/courses/mvp.jpg
  Course/images/courses/personal dev.jpg
  Course/images/courses/personal-growth1.jpg
  Course/images/courses/ratio_analysis.png
  Course/images/courses/spirituality.jpg
  Course/images/courses/stock market.jpg
  Course/images/courses/womm.jpg
  Course/images/img10.png
  Course/images/img11.png
  Course/images/img6.jpg
  Course/images/img7.png
  Course/images/img8.jpg
  Course/images/img9.jpg
  Course/subjects/Cyber Security.html
  Course/subjects/Data_Science.html
  Course/subjects/Finance.html
  Course/subjects/Marketing.html
  Course/subjects/Personal Growth.html
  Course/subjects/Spirituality.html
  contact/contact.html
Labels: good first issue, feature, Level2, GSSoC22

#380 Added Resources for Git and Github
  Course/images/courses/git.jpeg
  Course/subjects/computer_courses.html
  index.html
Labels: enhancement, good first issue, Level2, GSSoC22

#383 Replaced the template text in the login page
  log in/Login.html
Labels: good first issue, Level1, GSSoC22

#384 Added button for signin
  style.css
Labels: feature, Level2, GSSoC22

#386 Refactored Courses Footer Section
  Course/Courses.html
  Course/css/style.css
  Course/style.css
Labels: feature, Level2, GSSoC22

#388 sandhya#335
  css/main.css
  index.html
  style.css
Labels: enhancement, good first issue, Level1, GSSoC22

#396 Added social links in all course pages
  Course/subjects/Cyber Security.html
  Course/subjects/Data_Science.html
  Course/subjects/Finance.html
  Course/subjects/Marketing.html
  Course/subjects/Personal Growth.html
  Course/subjects/Spirituality.html
  Course/subjects/computer_courses.html
  Course/subjects/gate.html
  Course/subjects/jee.html
  Course/subjects/neet.html
Labels: enhancement, good first issue, Level1, GSSoC22

#393 Refactored Contact_Page
  contact/contact.html
  contact/css/style.css
Labels: feature, Level2, GSSoC22

#390 Refactored Team Page
  about/style.css
  about/team.html
Labels: good first issue, feature, Level1, GSSoC22

#398 Solved login page glitch
  log in/login.css
Labels: good first issue, feature, Level1, GSSoC22

#407 Made changes to feedback section
  about/style.css
  css/main.css
  css/responsive.css
  index.html
Labels: enhancement, good first issue, Level2, GSSoC22

#406 Added horizontal navbar in all pages
  Blog/blog.html
  Course/Courses.html
  about/team.html
  community/community.html
  contact/contact.html
  counselling/ counselling.html
  feature-pg/feature.html
  log in/Login.html
  navbar.css
Labels: enhancement, Level3, GSSoC22

#400 Improved Navbar of home and feature page
  feature-pg/assets/css/style.css
  style.css
Labels: enhancement, Level2, GSSoC22

#418 Teach button
  Course/Courses.html
  teach-on-bigb/teach.html
Labels: bug, good first issue, Level1, GSSoC22

#409 Refactored footer in feature page
  feature-pg/assets/css/style.css
  feature-pg/feature.html
Labels: good first issue, Level1, GSSoC22
