Repository The-Shivam-garg/BigB-E-learn-Websit-e, pull requests merged in 2022-02, with the labels that each got.

#23 Solved Link Issue in All Pages
  Blog/blog.html
  Course/Courses.html
  about/team.html
  contact/contact.html
  index.html
  log in/Login.html
Labels: enhancement, Jwoc, Medium: 2-3 days

#29 [Issue {24}] When we click on the Home button in Navbar while we are on the Home Page an error 404 page comes
  Blog/blog.html
  index.html
Labels: bug, Jwoc, Easy: 1 day

#31 [Issue:30] Feature: ADD a section in readme.md for showing the contributors .
  readme.md
Labels: feature, Jwoc, Easy: 1 day

#36 Added Preloader
  img/preloader.gif
  index.html
  style.css
Labels: help wanted, feature, Jwoc, Medium: 2-3 days

#39 issue #34 :- Made Read More Button linkable
  Blog/blog.html
  Blog/css/Style.css
Labels: enhancement, Jwoc, Easy: 1 day

#38 make homepage responsive
  css/responsive.css
  style.css
Labels: feature, Jwoc, Hard: 4 days

#41 updated UI for blog page
  .vscode/settings.json
  Blog/css/Style.css
Labels: enhancement, feature, Jwoc, Medium: 2-3 days

#48 Bigbpopup
  index.html
  newcourse.jpg
  style.css
Labels: feature, Jwoc, Hard: 4 days

#46 Illustration added on teach-on-BigB page
  teach-on-bigb/images/domains.png
Labels: good first issue, for review, feature, Jwoc

#43 Add more courses in course page #3
  Course/images/courses/PHP-MySQL.jpg
  Course/images/courses/reactjs.jpg
  Course/subjects/computer_courses.html
Labels: enhancement, good first issue, feature, Jwoc, Medium: 2-3 days

#51 Real Time Updation #27
  index.html
Labels: enhancement, feature, Jwoc, Medium: 2-3 days

#49 Implementation of the search button for courses
  Courses.html
  style.css
Labels: enhancement, feature, Jwoc, Hard: 4 days

#47 dark mode final
  Course/Courses.html
  Course/css/style.css
  Course/script.js
  Course/style.css
  app.js
  contact/contact.html
  contact/css/style.css
  css/main.css
Labels: feature, Jwoc, Hard: 4 days

#59 Create backend for join free online courses #25
  Course/subjects/Applied Science.html
  Course/subjects/Arts_Humanity.html
  Course/subjects/IT.html
  Course/subjects/Maths.html
  index.html
Labels: enhancement, feature, Jwoc, Hard: 4 days

#61 Teach-on-Bigb : Redirecting error 404 solved
  index.html
  teach-on-bigb/teach.html
Labels: bug, Jwoc, Medium: 2-3 days

#63 issue #9
  feature-pg/features.html
  index.html
Labels: enhancement, feature, Jwoc, Hard: 4 days

#71 Course popup responsiveness
  css/responsive.css
  index.html
  style.css
Labels: enhancement, feature, Jwoc, Easy: 1 day

#73 solved #34 no issue .
  .vscode/settings.json
  Blog/blog.html
  Blog/blog2.html
Labels: good first issue, feature, Jwoc, Easy: 1 day

#74 Adding Singin And Login Functionality
  log in/Login.html
  log in/login.js
  log in/signup.js
  log in/user_state.js
Labels: enhancement, feature, Jwoc, Hard: 4 days

#79 Updated responsiveness
  Course/css/style.css
  Course/style.css
  contact/css/style.css
Labels: enhancement, feature, Jwoc, Medium: 2-3 days

#84 Placeholder and hover effects
  css/main.css
  index.html
Labels: good first issue, feature, Jwoc, Easy: 1 day

#85 fixed #82
  contact/contact.html
Labels: feature, Easy: 1 day

#87 pop-up msg added
  index.html
Labels: feature, Jwoc, Medium: 2-3 days
