Repository The-Shivam-garg/BigB-E-learn-Websit-e, pull requests merged in 2022-03, with the labels that each got.

#91 Directed logo of website to the home page
  Blog/blog.html
  Blog/blog2.html
  Blog/blog3.html
  Course/subjects/computer_courses.html
  Course/subjects/gate.html
  Course/subjects/jee.html
  Course/subjects/quiz.html
  feature-pg/features.html
  index.html
Labels: feature, Jwoc, Medium: 2-3 days

#110 Fixed issue 92(Text-alignment)
  about/style.css
Labels: good first issue, Easy: 1 day, GSSOC

#118 Solved #95 no issue
  Blog/css/Style.css
Labels: good first issue, Jwoc, Easy: 1 day

#129 #109 issue solved
  index.html
  style.css
Labels: good first issue, Easy, GSSOC22

#125 docs: Added Code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, Easy, GSSOC22

#144 Updated Readme.md
  readme.md
Labels: enhancement, Easy, GSSOC22

#141 Why education UI updates
  css/main.css
  index.html
Labels: enhancement, feature, Hard: Level 3, GSSOC22

#139 Solved #94 no issue
  feature-pg/features.html
Labels: good first issue, Jwoc, Easy

#147 Fixes Issue #128
  Course/Courses.html
Labels: enhancement, good first issue, Easy, GSSOC22

#140 Added Email
  index.html
Labels: good first issue, Easy, GSSOC22

#145 Correction in image rendoring and codeblocks for git commands
  readme.md
Labels: enhancement, good first issue, Easy, GSSOC22

#152 Changed for BUG #146 "Inconsistency in blob radius"
  style.css
Labels: enhancement, good first issue, Easy, GSSOC22

#154 docs: Added Issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/doc_issue.yaml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation, good first issue, Easy, GSSOC22

#155 Add more relevant courses in the Course page
  Course/images/courses/Dbms-course.png
  Course/subjects/computer_courses.html
  readme.md
Labels: good first issue, feature, Easy, GSSOC22

#160 Fixes Issue #136
  css/main.css
Labels: good first issue, Medium: 2-3 days, GSSOC22

#166 Added card hover effect
  Blog/css/Style.css
  css/main.css
  feature-pg/features.css
Labels: enhancement, good first issue, Easy, GSSOC22

#164 Footer UI updated and Conflicts resolved
  css/main.css
  index.html
Labels: enhancement, good first issue, feature, Medium: 2-3 days, GSSOC22

#167 Spellcheck and wording issue #149
  Blog/blog.html
  Course/Courses.html
  feature-pg/features.html
  index.html
Labels: enhancement, good first issue, feature, Medium: 2-3 days, GSSOC22

#138 solved issue #135
  css/main.css
  css/utility.css
  style.css
Labels: good first issue, Easy, GSSOC22

#173 Improve Footer Text and Contact Us Fix issue #172
  Course/subjects/quiz.html
  contact/contact.html
  css/utility.css
Labels: bug, Medium: 2-3 days, GSSOC22

#169 Updated index.html to link Event page
  index.html
Labels: good first issue, Easy, GSSOC22

#177 issue #170 resolved - hover effect improved
  css/main.css
Labels: bug, good first issue, Easy, GSSOC22

#179 Made Responsive Team.htmlof about in Mobile View issue #178
  about/style.css
  style.css
Labels: enhancement, good first issue, Medium: 2-3 days, GSSOC22

#181 <Added separate section for NEET>
  Course/images/courses/Biology.png
  Course/images/courses/NEET-Question-Papers-PDF.jpg
  Course/images/courses/neetfavicon.jpg
  Course/samplePapers/neetpaper.pdf
  Course/subjects/computer_courses.html
  Course/subjects/gate.html
  Course/subjects/jee.html
  Course/subjects/neet.html
Labels: enhancement, good first issue, Medium: 2-3 days, GSSOC22

#180 Newsletter validation added
  index.html
Labels: enhancement, good first issue, Jwoc, Medium: 2-3 days

#188 Removed undefined random value error in console.log
  index.html
  style.css
Labels: enhancement, Hard: Level 3, GSSOC22

#184 Hover over footer
  css/main.css
  index.html
Labels: good first issue, feature, Easy, GSSOC22

#192 Changed Sign Up to Sign In
  Blog/blog.html
  Blog/blog2.html
  Blog/blog3.html
  Blog/js/BigWrapper.js
  Blog/js/FloatingButton.js
  Course/Courses.html
  Course/script1.js
  Course/script2.js
  Courses.html
  Events/events.html
  about/script1.js
  about/style1.css
  about/team.html
  contact/contact.html
  contact/css/style1.css
  css/courses.css
  feature-pg/features.html
  index.html
  js/FloatingButton.js
  js/courses1.js
  js/courses2.js
  js/preloader.js
  js/script1.js
  js/script2.js
  js/script3.js
  js/script4.js
  log in/Login.html
  log in/login.css
  log in/script1.js
  log in/script2.js
  log in/script3.js
  slick-1.8.1/index.html
  slick-1.8.1/script.js
  slick-1.8.1/styles.css
  teach-on-bigb/teach.html
Labels: enhancement, good first issue, Easy, GSSOC22

#189 issue #176 resolved - Dynamic year added in footer and readme.md file
  index.html
  readme.md
Labels: enhancement, good first issue, Easy, GSSOC22

#190 solved Issue#175
  style.css
Labels: enhancement, good first issue, Easy, GSSOC22

#194 fixed space in navbar and reduced it's height
  app.js
  index.html
  style.css
Labels: enhancement, good first issue, Easy, GSSOC22

#195 Background Updated
  css/main.css
Labels: enhancement, good first issue, Easy, GSSOC22

#201 make responsive signinpage and update blog page css issue #200
  Blog/css/Style.css
  log in/style.css
Labels: good first issue, Easy, GSSOC22

#207 Added round edges to "WHAT WE OFFER" section #204
  css/main.css
Labels: enhancement, good first issue, Easy, GSSOC22

#208 issue#197
  Blog/css/Style.css
  about/.vscode/settings.json
  css/main.css
  css/utility.css
  feature-pg/features.css
  style.css
Labels: enhancement, good first issue, Easy, GSSOC22

#206 toggle password visibility
  log in/Login.html
  log in/login.css
  log in/login.js
Labels: enhancement, good first issue, Easy, GSSOC22

#211 changed the color of icons in homepage
  style.css
Labels: good first issue, Easy, GSSOC22

#162 solved #137
  .vscode/settings.json
  Course/Courses.html
  Course/style.css
  contact/contact.html
  contact/css/style.css
Labels: good first issue, feature, Medium: 2-3 days, GSSOC22
