Repository The-Shivam-garg/BigB-E-learn-Websit-e, pull requests merged in 2022-04, with the labels that each got.

#235 Solved issue #226 . Text and hover color are different
  css/main.css
Labels: bug, enhancement, good first issue, Level1, GSSoC22

#232 confirm Password field added
  log in/Login.html
  log in/login.js
  log in/signup.js
Labels: bug, enhancement, feature, Level3, GSSoC22

#231 Readme updated
  readme.md
Labels: documentation, good first issue, Level1, GSSoC22

#234 Added smooth scroll in website
  Blog/css/Style.css
  Course/css/style.css
  Course/style.css
  Events/css/styles.css
  Events/features.css
  Resource_Page/css/resources.css
  Resource_Page/css/styles.css
  about/style.css
  about/style1.css
  contact/css/style.css
  contact/css/style1.css
  css/courses.css
  css/main.css
  css/utility.css
  log in/login.css
  log in/style.css
  slick-1.8.1/styles.css
  teach-on-bigb/teach.css
Labels: enhancement, good first issue, Level1, GSSoC22

#240 Made it appropriate
  css/main.css
Labels: enhancement, good first issue, Level1, GSSoC22

#249 Element is adjusted in Blog Section Navbar
  Blog/css/Style.css
Labels: good first issue, feature, Level1, GSSoC22

#251 Updated the links for footer
  feature-pg/feature.html
Labels: good first issue, feature, Level2, GSSoC22

#254 Improved footer
  css/main.css
  index.html
Labels: enhancement, feature, Level2, GSSoC22

#257 Blogs updated
  feature-pg/assets/css/style.css
  feature-pg/assets/images/blog 1.jpg
  feature-pg/assets/images/blog 2.jpg
  feature-pg/assets/images/blog 3.png
  feature-pg/feature.html
  feature-pg/features.css
  style.css
Labels: good first issue, feature, Level1, GSSoC22

#252 Hovereffects
  css/main.css
Labels: good first issue, feature, Level1, GSSoC22

#273 Added custom scrollbar
  Blog/css/Style.css
  Course/css/style.css
  contact/css/style.css
  style.css
Labels: feature, Level2, GSSoC22

#272 scrollToTop button added in feature page
  feature-pg/assets/css/style.css
  feature-pg/assets/js/script.js
  feature-pg/feature.html
Labels: good first issue, feature, Level2, GSSoC22

#286 New background image in the Feedback section
  contact/css/style.css
  css/main.css
  css/utility.css
  img/bg-image.jpg
  index.html
  style.css
Labels: enhancement, good first issue, Level1, GSSoC22

#277 fixed dark mode buton and explore section's links
  .vscode/settings.json
  Course/Courses.html
  index.html
  style.css
Labels: work in progress, Level1, GSSoC22

#284 Improved navbar
  style.css
Labels: good first issue, Level1, GSSoC22

#304 Smoothen Hover Transition
  css/main.css
Labels: good first issue, feature, Level1, GSSoC22

#305 Added animation on card hover
  css/main.css
Labels: enhancement, good first issue, Level1, GSSoC22

#281 links of courses added
  Course/subjects/Art_and_Design.html
  Course/subjects/Business_Strategy.html
  Course/subjects/Data_Science.html
  Course/subjects/Finance.html
  Course/subjects/Lifestyle.html
  Course/subjects/Marketing.html
  feature-pg/feature.html
Labels: enhancement, good first issue, Level1, GSSoC22

#316 Updating README.md file
  Thumbs.db
  readme.md
Labels: documentation, enhancement, good first issue, Level1, GSSoC22

#300 Footer
  index.html
  log in/style.css
Labels: bug, good first issue, work in progress, Level1, GSSoC22

#322 Created community page and linked to icon
  .DS_Store
  Blog/.DS_Store
  Course/.DS_Store
  Events/.DS_Store
  Resource_Page/.DS_Store
  about/.DS_Store
  community/.DS_Store
  community/assets/community image.jpeg
  community/assets/community-image.webp
  community/assets/v.png
  community/community.css
  community/community.html
  contact/.DS_Store
  css/utility.css
  index.html
Labels: feature, Level3, GSSoC22

#321 Refactored NavBar
  index.html
  style.css
Labels: enhancement, feature, Level2, GSSoC22

#312 Scroll to top button added in Courses page
  Course/Courses.html
  Course/script1.js
  Course/style.css
Labels: good first issue, feature, Level1, GSSoC22

#287 Changed the testimonial texts, names and images.
  img/pp1.jpg
  img/pp2.jpg
  img/pp3.jpg
  img/pp4.jpg
  index.html
Labels: enhancement, good first issue, Level1, GSSoC22

#332 sandhya#219
  css/main.css
  img/enroll.png
  index.html
Labels: enhancement, feature, Level2, GSSoC22

#330 Fixed the course images
  Course/Courses.html
  Course/css/style.css
  Course/images/img1.png
  Course/images/img2.png
  Course/images/img3.png
  Course/images/img4.png
  Course/images/img5.jpg
Labels: good first issue, feature, Level2, GSSoC22

#338 Fixed the main content
  index.html
Labels: enhancement, good first issue, Level1, GSSoC22

#339 Added links to buttons
  feature-pg/feature.html
Labels: enhancement, good first issue, Level1, GSSoC22

#337 Removed Padding in Contact Us
  contact/css/style1.css
Labels: enhancement, good first issue, Level1, GSSoC22

#344 Added navbar in feature page
  feature-pg/assets/css/style.css
  feature-pg/feature.html
Labels: enhancement, good first issue, Level1, GSSoC22

#343 Applying mobile responsivness on navbar
  index.html
  style.css
Labels: enhancement, feature, Level2, GSSoC22

#349 Social links added
  Blog/blog.html
  Blog/css/Style.css
  Course/Courses.html
  contact/contact.html
  index.html
  style.css
Labels: enhancement, good first issue, Level2, GSSoC22

#358 Improved the UI of 'Courses' page
  Course/Courses.html
  css/courses.css
  css/utility.css
Labels: enhancement, Level2, GSSoC22

#356 updated the hover effect and font of navbar
  feature-pg/assets/css/style.css
  index.html
  style.css
Labels: feature, Level1, GSSoC22

#355 Created counselling page with different images
  .DS_Store
  Blog/.DS_Store
  Course/.DS_Store
  Events/.DS_Store
  Resource_Page/.DS_Store
  about/.DS_Store
  community/.DS_Store
  contact/.DS_Store
  counselling/ counselling.html
  counselling/assets/counselling-image-1.webp
  counselling/assets/counselling-image-2.webp
  counselling/assets/v.png
  counselling/counselling.css
  index.html
Labels: enhancement, feature, Level3, GSSoC22

#353 Added feature option in side nav
  Course/Courses.html
  contact/contact.html
Labels: enhancement, Level1, GSSoC22

#351 rendering on clicked heading and learn more button aligned to center
  index.html
Labels: enhancement, good first issue, Level1, GSSoC22
